version: 2.1

commands:
  yarn-setup:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

executors:
  node:
    working_directory: ~/repo
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    docker:
      - image: circleci/node:10.13.0

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn-setup
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test:unit
      - run: yarn test:e2e

workflows:
  version: 2
  master_jobs:
    jobs:
      - test
